networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:latest
    container_name: load_test_influxdb
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    container_name: load_test_grafana
    depends_on:
      - influxdb
    networks:
      - grafana
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpass
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  # k6:
  #   image: grafana/k6
  #   ports:
  #     - "6565:6565"
  #   volumes:
  #     - "./tests:/tests"
  #   env_file: .env
  #   # environment:
  #   #   - K6_OUT=influxdb=http://influxdb:8086/k6
  #   # command: "version"

  k6:
    image: grafana/k6:latest
    container_name: load_test_k6
    depends_on:
      - grafana
    networks:
      - k6
    ports:
      - "6565:6565"
    env_file: .env
    # environment:
    #   - K6_OUT=influxdb=http://influxdb:8086
    volumes:
      - "./tests:/tests"

volumes:
  influx-db:
    driver: local
