networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:1.11
    container_name: load_test_influxdb
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:12.0.1
    container_name: load_test_grafana
    depends_on:
      - influxdb
    networks:
      - grafana
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpass
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  k6:
    image: grafana/k6:1.0.0
    container_name: load_test_k6
    depends_on:
      - grafana
    networks:
      - k6
    ports:
      - "6565:6565"
    env_file: .env
    volumes:
      - "./tests:/tests"

volumes:
  influx-db:
    driver: local
